/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.11.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QLabel *label;
    QLabel *ficha_4_3;
    QLabel *ficha_3_3;
    QLabel *label_4;
    QLabel *ficha_3_6;
    QLabel *ficha_1_4;
    QLabel *ficha_1_1;
    QLabel *ficha_2_1;
    QLabel *ficha_0_2;
    QLabel *ficha_1_5;
    QLabel *ficha_3_0;
    QLabel *ficha_0_5;
    QLabel *ficha_4_1;
    QLabel *ficha_4_6;
    QLabel *Jugador;
    QLabel *ficha_4_5;
    QLabel *ficha_1_3;
    QLabel *ficha_2_6;
    QLabel *conectado;
    QLabel *ficha_4_0;
    QLabel *ficha_0_6;
    QLabel *label_3;
    QLabel *ficha_4_2;
    QLabel *label_5;
    QLabel *ficha_3_2;
    QLabel *ficha_1_0;
    QLabel *ficha_2_4;
    QLabel *ficha_0_0;
    QLabel *ficha_2_0;
    QLabel *ficha_3_5;
    QLabel *ficha_2_2;
    QLabel *ficha_5_4;
    QLabel *ficha_3_1;
    QLabel *ficha_5_6;
    QLabel *ficha_0_1;
    QLabel *ficha_0_3;
    QLabel *ficha_0_4;
    QLabel *ficha_1_2;
    QLabel *ficha_1_6;
    QLabel *ficha_2_3;
    QLabel *ficha_2_5;
    QLabel *ficha_3_4;
    QLabel *ficha_4_4;
    QLabel *ficha_5_0;
    QLabel *ficha_5_1;
    QLabel *ficha_5_2;
    QLabel *ficha_5_3;
    QLabel *ficha_5_5;
    QLabel *label_6;
    QLabel *texto_j_a_2;
    QLabel *texto_j_b_2;
    QLabel *ficha_actual;
    QLabel *texto_j_b_3;
    QPushButton *Btn_c_1;
    QPushButton *Btn_c_2;
    QPushButton *Btn_c_3;
    QPushButton *Btn_c_4;
    QPushButton *Btn_c_5;
    QPushButton *Btn_c_6;
    QPushButton *Btn_c_7;
    QLabel *fin1;
    QLabel *fin2;
    QLabel *fin3;
    QMenuBar *menuBar;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(703, 606);
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        label = new QLabel(centralWidget);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(0, 0, 691, 531));
        label->setPixmap(QPixmap(QString::fromUtf8(":/imagenes/conecta-4.png")));
        label->setScaledContents(true);
        ficha_4_3 = new QLabel(centralWidget);
        ficha_4_3->setObjectName(QStringLiteral("ficha_4_3"));
        ficha_4_3->setGeometry(QRect(260, 330, 71, 71));
        ficha_4_3->setPixmap(QPixmap(QString::fromUtf8(":/imagenes/vacio.png")));
        ficha_4_3->setScaledContents(true);
        ficha_3_3 = new QLabel(centralWidget);
        ficha_3_3->setObjectName(QStringLiteral("ficha_3_3"));
        ficha_3_3->setGeometry(QRect(260, 260, 71, 71));
        ficha_3_3->setPixmap(QPixmap(QString::fromUtf8(":/imagenes/vacio.png")));
        ficha_3_3->setScaledContents(true);
        label_4 = new QLabel(centralWidget);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(250, 410, 21, 71));
        label_4->setPixmap(QPixmap(QString::fromUtf8(":/imagenes/fondo2.png")));
        label_4->setScaledContents(true);
        ficha_3_6 = new QLabel(centralWidget);
        ficha_3_6->setObjectName(QStringLiteral("ficha_3_6"));
        ficha_3_6->setGeometry(QRect(470, 260, 71, 71));
        ficha_3_6->setPixmap(QPixmap(QString::fromUtf8(":/imagenes/vacio.png")));
        ficha_3_6->setScaledContents(true);
        ficha_1_4 = new QLabel(centralWidget);
        ficha_1_4->setObjectName(QStringLiteral("ficha_1_4"));
        ficha_1_4->setGeometry(QRect(330, 120, 71, 71));
        ficha_1_4->setPixmap(QPixmap(QString::fromUtf8(":/imagenes/vacio.png")));
        ficha_1_4->setScaledContents(true);
        ficha_1_1 = new QLabel(centralWidget);
        ficha_1_1->setObjectName(QStringLiteral("ficha_1_1"));
        ficha_1_1->setGeometry(QRect(110, 120, 71, 71));
        ficha_1_1->setPixmap(QPixmap(QString::fromUtf8(":/imagenes/vacio.png")));
        ficha_1_1->setScaledContents(true);
        ficha_2_1 = new QLabel(centralWidget);
        ficha_2_1->setObjectName(QStringLiteral("ficha_2_1"));
        ficha_2_1->setGeometry(QRect(110, 190, 71, 71));
        ficha_2_1->setPixmap(QPixmap(QString::fromUtf8(":/imagenes/vacio.png")));
        ficha_2_1->setScaledContents(true);
        ficha_0_2 = new QLabel(centralWidget);
        ficha_0_2->setObjectName(QStringLiteral("ficha_0_2"));
        ficha_0_2->setGeometry(QRect(180, 50, 71, 71));
        ficha_0_2->setPixmap(QPixmap(QString::fromUtf8(":/imagenes/vacio.png")));
        ficha_0_2->setScaledContents(true);
        ficha_1_5 = new QLabel(centralWidget);
        ficha_1_5->setObjectName(QStringLiteral("ficha_1_5"));
        ficha_1_5->setGeometry(QRect(400, 120, 71, 71));
        ficha_1_5->setPixmap(QPixmap(QString::fromUtf8(":/imagenes/vacio.png")));
        ficha_1_5->setScaledContents(true);
        ficha_3_0 = new QLabel(centralWidget);
        ficha_3_0->setObjectName(QStringLiteral("ficha_3_0"));
        ficha_3_0->setGeometry(QRect(40, 260, 71, 71));
        ficha_3_0->setPixmap(QPixmap(QString::fromUtf8(":/imagenes/vacio.png")));
        ficha_3_0->setScaledContents(true);
        ficha_0_5 = new QLabel(centralWidget);
        ficha_0_5->setObjectName(QStringLiteral("ficha_0_5"));
        ficha_0_5->setGeometry(QRect(400, 50, 71, 71));
        ficha_0_5->setPixmap(QPixmap(QString::fromUtf8(":/imagenes/vacio.png")));
        ficha_0_5->setScaledContents(true);
        ficha_4_1 = new QLabel(centralWidget);
        ficha_4_1->setObjectName(QStringLiteral("ficha_4_1"));
        ficha_4_1->setGeometry(QRect(110, 330, 71, 71));
        ficha_4_1->setPixmap(QPixmap(QString::fromUtf8(":/imagenes/vacio.png")));
        ficha_4_1->setScaledContents(true);
        ficha_4_6 = new QLabel(centralWidget);
        ficha_4_6->setObjectName(QStringLiteral("ficha_4_6"));
        ficha_4_6->setGeometry(QRect(470, 330, 71, 71));
        ficha_4_6->setPixmap(QPixmap(QString::fromUtf8(":/imagenes/vacio.png")));
        ficha_4_6->setScaledContents(true);
        Jugador = new QLabel(centralWidget);
        Jugador->setObjectName(QStringLiteral("Jugador"));
        Jugador->setGeometry(QRect(560, 250, 101, 20));
        ficha_4_5 = new QLabel(centralWidget);
        ficha_4_5->setObjectName(QStringLiteral("ficha_4_5"));
        ficha_4_5->setGeometry(QRect(400, 330, 71, 71));
        ficha_4_5->setPixmap(QPixmap(QString::fromUtf8(":/imagenes/vacio.png")));
        ficha_4_5->setScaledContents(true);
        ficha_1_3 = new QLabel(centralWidget);
        ficha_1_3->setObjectName(QStringLiteral("ficha_1_3"));
        ficha_1_3->setGeometry(QRect(260, 120, 71, 71));
        ficha_1_3->setPixmap(QPixmap(QString::fromUtf8(":/imagenes/vacio.png")));
        ficha_1_3->setScaledContents(true);
        ficha_2_6 = new QLabel(centralWidget);
        ficha_2_6->setObjectName(QStringLiteral("ficha_2_6"));
        ficha_2_6->setGeometry(QRect(470, 190, 71, 71));
        ficha_2_6->setPixmap(QPixmap(QString::fromUtf8(":/imagenes/vacio.png")));
        ficha_2_6->setScaledContents(true);
        conectado = new QLabel(centralWidget);
        conectado->setObjectName(QStringLiteral("conectado"));
        conectado->setGeometry(QRect(560, 290, 101, 20));
        ficha_4_0 = new QLabel(centralWidget);
        ficha_4_0->setObjectName(QStringLiteral("ficha_4_0"));
        ficha_4_0->setGeometry(QRect(40, 330, 71, 71));
        ficha_4_0->setPixmap(QPixmap(QString::fromUtf8(":/imagenes/vacio.png")));
        ficha_4_0->setScaledContents(true);
        ficha_0_6 = new QLabel(centralWidget);
        ficha_0_6->setObjectName(QStringLiteral("ficha_0_6"));
        ficha_0_6->setGeometry(QRect(470, 50, 71, 71));
        ficha_0_6->setPixmap(QPixmap(QString::fromUtf8(":/imagenes/vacio.png")));
        ficha_0_6->setScaledContents(true);
        label_3 = new QLabel(centralWidget);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(390, 400, 151, 21));
        label_3->setPixmap(QPixmap(QString::fromUtf8(":/imagenes/fondo2.png")));
        label_3->setScaledContents(true);
        ficha_4_2 = new QLabel(centralWidget);
        ficha_4_2->setObjectName(QStringLiteral("ficha_4_2"));
        ficha_4_2->setGeometry(QRect(180, 330, 71, 71));
        ficha_4_2->setPixmap(QPixmap(QString::fromUtf8(":/imagenes/vacio.png")));
        ficha_4_2->setScaledContents(true);
        label_5 = new QLabel(centralWidget);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(550, 110, 111, 301));
        label_5->setPixmap(QPixmap(QString::fromUtf8(":/imagenes/cuadroblanco.png")));
        label_5->setScaledContents(true);
        ficha_3_2 = new QLabel(centralWidget);
        ficha_3_2->setObjectName(QStringLiteral("ficha_3_2"));
        ficha_3_2->setGeometry(QRect(180, 260, 71, 71));
        ficha_3_2->setPixmap(QPixmap(QString::fromUtf8(":/imagenes/vacio.png")));
        ficha_3_2->setScaledContents(true);
        ficha_1_0 = new QLabel(centralWidget);
        ficha_1_0->setObjectName(QStringLiteral("ficha_1_0"));
        ficha_1_0->setGeometry(QRect(40, 120, 71, 71));
        ficha_1_0->setPixmap(QPixmap(QString::fromUtf8(":/imagenes/vacio.png")));
        ficha_1_0->setScaledContents(true);
        ficha_2_4 = new QLabel(centralWidget);
        ficha_2_4->setObjectName(QStringLiteral("ficha_2_4"));
        ficha_2_4->setGeometry(QRect(330, 190, 71, 71));
        ficha_2_4->setPixmap(QPixmap(QString::fromUtf8(":/imagenes/vacio.png")));
        ficha_2_4->setScaledContents(true);
        ficha_0_0 = new QLabel(centralWidget);
        ficha_0_0->setObjectName(QStringLiteral("ficha_0_0"));
        ficha_0_0->setGeometry(QRect(40, 50, 71, 71));
        ficha_0_0->setPixmap(QPixmap(QString::fromUtf8(":/imagenes/vacio.png")));
        ficha_0_0->setScaledContents(true);
        ficha_2_0 = new QLabel(centralWidget);
        ficha_2_0->setObjectName(QStringLiteral("ficha_2_0"));
        ficha_2_0->setGeometry(QRect(40, 190, 71, 71));
        ficha_2_0->setPixmap(QPixmap(QString::fromUtf8(":/imagenes/vacio.png")));
        ficha_2_0->setScaledContents(true);
        ficha_3_5 = new QLabel(centralWidget);
        ficha_3_5->setObjectName(QStringLiteral("ficha_3_5"));
        ficha_3_5->setGeometry(QRect(400, 260, 71, 71));
        ficha_3_5->setPixmap(QPixmap(QString::fromUtf8(":/imagenes/vacio.png")));
        ficha_3_5->setScaledContents(true);
        ficha_2_2 = new QLabel(centralWidget);
        ficha_2_2->setObjectName(QStringLiteral("ficha_2_2"));
        ficha_2_2->setGeometry(QRect(180, 190, 71, 71));
        ficha_2_2->setPixmap(QPixmap(QString::fromUtf8(":/imagenes/vacio.png")));
        ficha_2_2->setScaledContents(true);
        ficha_5_4 = new QLabel(centralWidget);
        ficha_5_4->setObjectName(QStringLiteral("ficha_5_4"));
        ficha_5_4->setGeometry(QRect(330, 410, 71, 71));
        ficha_5_4->setPixmap(QPixmap(QString::fromUtf8(":/imagenes/vacio.png")));
        ficha_5_4->setScaledContents(true);
        ficha_3_1 = new QLabel(centralWidget);
        ficha_3_1->setObjectName(QStringLiteral("ficha_3_1"));
        ficha_3_1->setGeometry(QRect(110, 260, 71, 71));
        ficha_3_1->setPixmap(QPixmap(QString::fromUtf8(":/imagenes/vacio.png")));
        ficha_3_1->setScaledContents(true);
        ficha_5_6 = new QLabel(centralWidget);
        ficha_5_6->setObjectName(QStringLiteral("ficha_5_6"));
        ficha_5_6->setGeometry(QRect(470, 410, 71, 71));
        ficha_5_6->setPixmap(QPixmap(QString::fromUtf8(":/imagenes/vacio.png")));
        ficha_5_6->setScaledContents(true);
        ficha_0_1 = new QLabel(centralWidget);
        ficha_0_1->setObjectName(QStringLiteral("ficha_0_1"));
        ficha_0_1->setGeometry(QRect(110, 50, 71, 71));
        ficha_0_1->setPixmap(QPixmap(QString::fromUtf8(":/imagenes/vacio.png")));
        ficha_0_1->setScaledContents(true);
        ficha_0_3 = new QLabel(centralWidget);
        ficha_0_3->setObjectName(QStringLiteral("ficha_0_3"));
        ficha_0_3->setGeometry(QRect(260, 50, 71, 71));
        ficha_0_3->setPixmap(QPixmap(QString::fromUtf8(":/imagenes/vacio.png")));
        ficha_0_3->setScaledContents(true);
        ficha_0_4 = new QLabel(centralWidget);
        ficha_0_4->setObjectName(QStringLiteral("ficha_0_4"));
        ficha_0_4->setGeometry(QRect(330, 50, 71, 71));
        ficha_0_4->setPixmap(QPixmap(QString::fromUtf8(":/imagenes/vacio.png")));
        ficha_0_4->setScaledContents(true);
        ficha_1_2 = new QLabel(centralWidget);
        ficha_1_2->setObjectName(QStringLiteral("ficha_1_2"));
        ficha_1_2->setGeometry(QRect(180, 120, 71, 71));
        ficha_1_2->setPixmap(QPixmap(QString::fromUtf8(":/imagenes/vacio.png")));
        ficha_1_2->setScaledContents(true);
        ficha_1_6 = new QLabel(centralWidget);
        ficha_1_6->setObjectName(QStringLiteral("ficha_1_6"));
        ficha_1_6->setGeometry(QRect(470, 120, 71, 71));
        ficha_1_6->setPixmap(QPixmap(QString::fromUtf8(":/imagenes/vacio.png")));
        ficha_1_6->setScaledContents(true);
        ficha_2_3 = new QLabel(centralWidget);
        ficha_2_3->setObjectName(QStringLiteral("ficha_2_3"));
        ficha_2_3->setGeometry(QRect(260, 190, 71, 71));
        ficha_2_3->setPixmap(QPixmap(QString::fromUtf8(":/imagenes/vacio.png")));
        ficha_2_3->setScaledContents(true);
        ficha_2_5 = new QLabel(centralWidget);
        ficha_2_5->setObjectName(QStringLiteral("ficha_2_5"));
        ficha_2_5->setGeometry(QRect(400, 190, 71, 71));
        ficha_2_5->setPixmap(QPixmap(QString::fromUtf8(":/imagenes/vacio.png")));
        ficha_2_5->setScaledContents(true);
        ficha_3_4 = new QLabel(centralWidget);
        ficha_3_4->setObjectName(QStringLiteral("ficha_3_4"));
        ficha_3_4->setGeometry(QRect(330, 260, 71, 71));
        ficha_3_4->setPixmap(QPixmap(QString::fromUtf8(":/imagenes/vacio.png")));
        ficha_3_4->setScaledContents(true);
        ficha_4_4 = new QLabel(centralWidget);
        ficha_4_4->setObjectName(QStringLiteral("ficha_4_4"));
        ficha_4_4->setGeometry(QRect(330, 330, 71, 71));
        ficha_4_4->setPixmap(QPixmap(QString::fromUtf8(":/imagenes/vacio.png")));
        ficha_4_4->setScaledContents(true);
        ficha_5_0 = new QLabel(centralWidget);
        ficha_5_0->setObjectName(QStringLiteral("ficha_5_0"));
        ficha_5_0->setGeometry(QRect(40, 410, 71, 71));
        ficha_5_0->setPixmap(QPixmap(QString::fromUtf8(":/imagenes/vacio.png")));
        ficha_5_0->setScaledContents(true);
        ficha_5_1 = new QLabel(centralWidget);
        ficha_5_1->setObjectName(QStringLiteral("ficha_5_1"));
        ficha_5_1->setGeometry(QRect(110, 410, 71, 71));
        ficha_5_1->setPixmap(QPixmap(QString::fromUtf8(":/imagenes/vacio.png")));
        ficha_5_1->setScaledContents(true);
        ficha_5_2 = new QLabel(centralWidget);
        ficha_5_2->setObjectName(QStringLiteral("ficha_5_2"));
        ficha_5_2->setGeometry(QRect(180, 410, 71, 71));
        ficha_5_2->setPixmap(QPixmap(QString::fromUtf8(":/imagenes/vacio.png")));
        ficha_5_2->setScaledContents(true);
        ficha_5_3 = new QLabel(centralWidget);
        ficha_5_3->setObjectName(QStringLiteral("ficha_5_3"));
        ficha_5_3->setGeometry(QRect(260, 410, 71, 71));
        ficha_5_3->setPixmap(QPixmap(QString::fromUtf8(":/imagenes/vacio.png")));
        ficha_5_3->setScaledContents(true);
        ficha_5_5 = new QLabel(centralWidget);
        ficha_5_5->setObjectName(QStringLiteral("ficha_5_5"));
        ficha_5_5->setGeometry(QRect(400, 410, 71, 71));
        ficha_5_5->setPixmap(QPixmap(QString::fromUtf8(":/imagenes/vacio.png")));
        ficha_5_5->setScaledContents(true);
        label_6 = new QLabel(centralWidget);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(40, 0, 261, 41));
        QFont font;
        font.setPointSize(20);
        label_6->setFont(font);
        texto_j_a_2 = new QLabel(centralWidget);
        texto_j_a_2->setObjectName(QStringLiteral("texto_j_a_2"));
        texto_j_a_2->setGeometry(QRect(560, 130, 101, 20));
        texto_j_b_2 = new QLabel(centralWidget);
        texto_j_b_2->setObjectName(QStringLiteral("texto_j_b_2"));
        texto_j_b_2->setGeometry(QRect(560, 160, 101, 20));
        ficha_actual = new QLabel(centralWidget);
        ficha_actual->setObjectName(QStringLiteral("ficha_actual"));
        ficha_actual->setGeometry(QRect(570, 280, 71, 71));
        ficha_actual->setScaledContents(true);
        texto_j_b_3 = new QLabel(centralWidget);
        texto_j_b_3->setObjectName(QStringLiteral("texto_j_b_3"));
        texto_j_b_3->setGeometry(QRect(560, 240, 101, 20));
        Btn_c_1 = new QPushButton(centralWidget);
        Btn_c_1->setObjectName(QStringLiteral("Btn_c_1"));
        Btn_c_1->setEnabled(false);
        Btn_c_1->setGeometry(QRect(50, 490, 41, 25));
        Btn_c_2 = new QPushButton(centralWidget);
        Btn_c_2->setObjectName(QStringLiteral("Btn_c_2"));
        Btn_c_2->setEnabled(false);
        Btn_c_2->setGeometry(QRect(120, 490, 41, 25));
        Btn_c_3 = new QPushButton(centralWidget);
        Btn_c_3->setObjectName(QStringLiteral("Btn_c_3"));
        Btn_c_3->setEnabled(false);
        Btn_c_3->setGeometry(QRect(200, 490, 41, 25));
        Btn_c_4 = new QPushButton(centralWidget);
        Btn_c_4->setObjectName(QStringLiteral("Btn_c_4"));
        Btn_c_4->setEnabled(false);
        Btn_c_4->setGeometry(QRect(280, 490, 41, 25));
        Btn_c_5 = new QPushButton(centralWidget);
        Btn_c_5->setObjectName(QStringLiteral("Btn_c_5"));
        Btn_c_5->setEnabled(false);
        Btn_c_5->setGeometry(QRect(350, 490, 41, 25));
        Btn_c_6 = new QPushButton(centralWidget);
        Btn_c_6->setObjectName(QStringLiteral("Btn_c_6"));
        Btn_c_6->setEnabled(false);
        Btn_c_6->setGeometry(QRect(420, 490, 41, 25));
        Btn_c_7 = new QPushButton(centralWidget);
        Btn_c_7->setObjectName(QStringLiteral("Btn_c_7"));
        Btn_c_7->setEnabled(false);
        Btn_c_7->setGeometry(QRect(490, 490, 41, 25));
        fin1 = new QLabel(centralWidget);
        fin1->setObjectName(QStringLiteral("fin1"));
        fin1->setGeometry(QRect(40, 50, 501, 431));
        fin1->setScaledContents(true);
        fin2 = new QLabel(centralWidget);
        fin2->setObjectName(QStringLiteral("fin2"));
        fin2->setGeometry(QRect(190, 110, 271, 71));
        QFont font1;
        font1.setPointSize(30);
        fin2->setFont(font1);
        fin3 = new QLabel(centralWidget);
        fin3->setObjectName(QStringLiteral("fin3"));
        fin3->setGeometry(QRect(190, 200, 221, 171));
        fin3->setScaledContents(true);
        MainWindow->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 703, 22));
        MainWindow->setMenuBar(menuBar);
        mainToolBar = new QToolBar(MainWindow);
        mainToolBar->setObjectName(QStringLiteral("mainToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        MainWindow->setStatusBar(statusBar);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", nullptr));
        label->setText(QString());
        ficha_4_3->setText(QString());
        ficha_3_3->setText(QString());
        label_4->setText(QString());
        ficha_3_6->setText(QString());
        ficha_1_4->setText(QString());
        ficha_1_1->setText(QString());
        ficha_2_1->setText(QString());
        ficha_0_2->setText(QString());
        ficha_1_5->setText(QString());
        ficha_3_0->setText(QString());
        ficha_0_5->setText(QString());
        ficha_4_1->setText(QString());
        ficha_4_6->setText(QString());
        Jugador->setText(QString());
        ficha_4_5->setText(QString());
        ficha_1_3->setText(QString());
        ficha_2_6->setText(QString());
        conectado->setText(QString());
        ficha_4_0->setText(QString());
        ficha_0_6->setText(QString());
        label_3->setText(QString());
        ficha_4_2->setText(QString());
        label_5->setText(QString());
        ficha_3_2->setText(QString());
        ficha_1_0->setText(QString());
        ficha_2_4->setText(QString());
        ficha_0_0->setText(QString());
        ficha_2_0->setText(QString());
        ficha_3_5->setText(QString());
        ficha_2_2->setText(QString());
        ficha_5_4->setText(QString());
        ficha_3_1->setText(QString());
        ficha_5_6->setText(QString());
        ficha_0_1->setText(QString());
        ficha_0_3->setText(QString());
        ficha_0_4->setText(QString());
        ficha_1_2->setText(QString());
        ficha_1_6->setText(QString());
        ficha_2_3->setText(QString());
        ficha_2_5->setText(QString());
        ficha_3_4->setText(QString());
        ficha_4_4->setText(QString());
        ficha_5_0->setText(QString());
        ficha_5_1->setText(QString());
        ficha_5_2->setText(QString());
        ficha_5_3->setText(QString());
        ficha_5_5->setText(QString());
        label_6->setText(QApplication::translate("MainWindow", "4 EN LINEA", nullptr));
        texto_j_a_2->setText(QString());
        texto_j_b_2->setText(QString());
        ficha_actual->setText(QString());
        texto_j_b_3->setText(QString());
        Btn_c_1->setText(QApplication::translate("MainWindow", "C1", nullptr));
        Btn_c_2->setText(QApplication::translate("MainWindow", "C2", nullptr));
        Btn_c_3->setText(QApplication::translate("MainWindow", "C3", nullptr));
        Btn_c_4->setText(QApplication::translate("MainWindow", "C4", nullptr));
        Btn_c_5->setText(QApplication::translate("MainWindow", "C5", nullptr));
        Btn_c_6->setText(QApplication::translate("MainWindow", "C6", nullptr));
        Btn_c_7->setText(QApplication::translate("MainWindow", "C7", nullptr));
        fin1->setText(QString());
        fin2->setText(QString());
        fin3->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
